import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { setTodoDoneRequestSchema } from "@/lib/todo-api";
import { setTodoDoneFor } from "@/lib/todo-tools";

/**
 * Completing one item, and reopening it: `done: false` is the undo, so there is
 * deliberately no DELETE. Same bearer-or-cookie gate as the collection route
 * above it; `RouteContext` is a global generated by `next dev`/`next build`.
 */
export async function PATCH(
  request: Request,
  context: RouteContext<"/api/todos/[id]">,
) {
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return Response.json({ error: "unauthorized" }, { status: 401 });
  }

  const body = setTodoDoneRequestSchema.safeParse(
    await request.json().catch(() => null),
  );
  if (!body.success) {
    return Response.json({ error: "invalid body" }, { status: 400 });
  }

  const { id } = await context.params;
  const todo = await setTodoDoneFor(db, session.user.id, id, body.data.done);
  // Another user's item is invisible rather than forbidden, so this is a 404
  // for a stolen id just as it is for one that never existed.
  if (!todo) {
    return Response.json({ error: "not found" }, { status: 404 });
  }

  return Response.json({ todo });
}
